# This is a basic workflow to help you get started with Actions

name: NetfilterFirewall

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # 环境
      #- name: Install Qt
       # uses: jurplel/install-qt-action@v2
        #with:
          # 安装目录,默认当前路径
          #dir: # optional
          # 版本,默认最新的LTS(5.12.6)
          #version: 5.3.1
          # 编译平台。一般不修改。
          #host: # optional
          # 目标平台。默认desktop，可选android、ios
          #target: desktop
          # 架构
          #arch: linux_x64
      
      #set platform
      #- name: set platform
        #run: sudo apt install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0
       # run: |
          #export QT_DEBUG_PLUGINS=1
          #qtcreator
          #sudo apt-get install libx11-dev libxext-dev libxtst-dev 
          #sudo apt-get install xlibmesa-gl-dev libglu1-mesa-dev
          #qmake -version
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

        
      # kernel目录下进行的操作
      - name: actions beside kernel
        run: |
          cd kernel
          pwd
          make
          sudo insmod NetfilterFirewall.ko
          sudo mknod NetfilterFirewall c 250 0
          sudo chmod 777 NetfilterFirewall
          gcc firewall.cpp -lstdc++ -o firewall
          ./firewall

      #dest目录下进行的操作
      #- name: actions beside dest
        #run: |
          #cd dest
          #pwd
         # sudo chmod 777 fpNetfilterFirewall
          #ls -l
          #./fpNetfilterFirewall
        
  
    
      
          
           

      
      
      
          
