# This is a basic workflow to help you get started with Actions

name: NetfilterFirewall

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      # kernel目录下进行的操作
      - name: actions beside kernel
        run: |
          cd kernel
          pwd
          touch ko
          ls
          sudo insmod NetfilterFirewall.ko
          sudo mknod fpNetfilterFirewall c 250 0
      # 查看日志
      - name: log
        run: dmesg
          
           

      
      
      
          
