# This is a basic workflow to help you get started with Actions

name: NetfilterFirewall

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # 环境
      - name: 'Set up QT'
        uses: jurplel/install-qt-action@v2 
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      #platform
      - name: platform
        run: sudo apt-get install libxcb-xinerama0
        
      # kernel目录下进行的操作
      - name: actions beside kernel
        run: |
          cd kernel
          pwd
          make
          sudo insmod NetfilterFirewall.ko
          sudo mknod NetfilterFirewall c 250 0
          sudo chmod 777 NetfilterFirewall

      #dest目录下进行的操作
      - name: actions beside dest
        run: |
          cd dest
          pwd
          sudo chmod 777 fpNetfilterFirewall
          ls -l
          ./fpNetfilterFirewall
        
  
    
      
          
           

      
      
      
          
